@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class StatusBarFooter
Class CommandBox
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class MeetingListPanel
Class MeetingCard
}

package Model <<Rectangle>> {
Class Contact
Class Meeting
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" MeetingListPanel
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "1" HelpWindow

PersonListPanel -down-> "*" PersonCard
MeetingListPanel --down-> "*" MeetingCard

MainWindow --down--|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
MeetingListPanel --|> UiPart
MeetingCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

MeetingCard ..> Meeting
PersonCard ..> Contact
UiManager -right-> Logic
MainWindow -left-> Logic

MeetingCard -[hidden]left- PersonCard
MeetingListPanel -[hidden]left- PersonListPanel
PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
