@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters unarchive command in the command box;
:AddressBookParser parses the command;
:UnarchiveCommandParser parses the arguments
                    (meeting index);

if () then ([arguments are valid])
if () then ([else])
    :AddresSoc displays
    error message;
else ([is archived])
    :Unarchive Meeting;

endif
else ([else])
:Throws ParseException with invalid command\nformat message and command usage;
endif
stop
@enduml
